# Generated by Django 3.0.6 on 2020-06-05 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller_product',
            old_name='sel_pro_id',
            new_name='sid',
        ),
        migrations.AddField(
            model_name='seller_product',
            name='veg_id',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='market.Vegitables'),
            preserve_default=False,
        ),
    ]
